export const MAIN_PAGE = '/products'
export const PRODUCTS_PAGE = '/products/:id'
export const PROFILE = '/profile'
export const CHECKOUT = '/checkout'
export const CHECKOUT_CREATED = '/success_checkout'
export const RESET_PASSWORD = '/reset-password/:token'
export const NOT_FOUND = '/'
