export const MAIN_PAGE = '/'
export const PRODUCTS_PAGE = '/:id'
export const PROFILE = '/profile'
export const CHECKOUT = '/checkout'
export const CHECKOUT_CREATED = '/success_checkout'
export const RESET_PASSWORD = '/reset-password/:token'
